2021-12-19 10:10:13 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration hildebrandglow_dcc which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-12-19 10:10:13 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration nodered which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-12-19 10:10:22 ERROR (MainThread) [snitun.client.client_peer] Challenge/Response error with SniTun server (0 bytes read on a total of 32 expected bytes)
2021-12-19 10:10:22 ERROR (MainThread) [hass_nabucasa.remote] Connection problem to snitun server
2021-12-19 10:10:23 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.forest_room_sensor_battery_level (<class 'custom_components.nodered.sensor.NodeRedSensor'>) implements device_state_attributes. Please report it to the custom component author.
2021-12-19 10:10:23 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.forest_room_lux_level (<class 'custom_components.nodered.sensor.NodeRedSensor'>) implements device_state_attributes. Please report it to the custom component author.
2021-12-19 10:10:24 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.backup_free_disk_space_in_gb (<class 'custom_components.nodered.sensor.NodeRedSensor'>) implements device_state_attributes. Please report it to the custom component author.
2021-12-19 10:10:24 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.backup_percent_of_disk_used (<class 'custom_components.nodered.sensor.NodeRedSensor'>) implements device_state_attributes. Please report it to the custom component author.
2021-12-19 10:10:24 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.pineapple_free_disk_space_in_gb (<class 'custom_components.nodered.sensor.NodeRedSensor'>) implements device_state_attributes. Please report it to the custom component author.
2021-12-19 10:10:24 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.pineapple_percent_of_disk_used (<class 'custom_components.nodered.sensor.NodeRedSensor'>) implements device_state_attributes. Please report it to the custom component author.
2021-12-19 10:10:24 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.blueberry_free_disk_space_in_gb (<class 'custom_components.nodered.sensor.NodeRedSensor'>) implements device_state_attributes. Please report it to the custom component author.
2021-12-19 10:10:25 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.blueberry_percent_of_disk_used (<class 'custom_components.nodered.sensor.NodeRedSensor'>) implements device_state_attributes. Please report it to the custom component author.
2021-12-19 10:10:25 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.blueberry_boot_free_disk_space_in_gb (<class 'custom_components.nodered.sensor.NodeRedSensor'>) implements device_state_attributes. Please report it to the custom component author.
2021-12-19 10:10:25 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.blueberry_boot_percent_of_disk_used (<class 'custom_components.nodered.sensor.NodeRedSensor'>) implements device_state_attributes. Please report it to the custom component author.
2021-12-19 10:10:25 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.peewee_free_disk_space_in_gb (<class 'custom_components.nodered.sensor.NodeRedSensor'>) implements device_state_attributes. Please report it to the custom component author.
2021-12-19 10:10:25 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.peewee_percent_of_disk_used (<class 'custom_components.nodered.sensor.NodeRedSensor'>) implements device_state_attributes. Please report it to the custom component author.
2021-12-19 10:10:25 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.peewee_boot_free_disk_space_in_gb (<class 'custom_components.nodered.sensor.NodeRedSensor'>) implements device_state_attributes. Please report it to the custom component author.
2021-12-19 10:10:25 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.peewee_boot_percent_of_disk_used (<class 'custom_components.nodered.sensor.NodeRedSensor'>) implements device_state_attributes. Please report it to the custom component author.
2021-12-19 10:10:25 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.ringding_free_disk_space_in_gb (<class 'custom_components.nodered.sensor.NodeRedSensor'>) implements device_state_attributes. Please report it to the custom component author.
2021-12-19 10:10:25 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.ringding_percent_of_disk_used (<class 'custom_components.nodered.sensor.NodeRedSensor'>) implements device_state_attributes. Please report it to the custom component author.
2021-12-19 10:10:25 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.ringding_boot_free_disk_space_in_gb (<class 'custom_components.nodered.sensor.NodeRedSensor'>) implements device_state_attributes. Please report it to the custom component author.
2021-12-19 10:10:25 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.ringding_boot_percent_of_disk_used (<class 'custom_components.nodered.sensor.NodeRedSensor'>) implements device_state_attributes. Please report it to the custom component author.
2021-12-19 10:10:25 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.watermelon_free_disk_space_in_gb (<class 'custom_components.nodered.sensor.NodeRedSensor'>) implements device_state_attributes. Please report it to the custom component author.
2021-12-19 10:10:25 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.watermelon_percent_of_disk_used (<class 'custom_components.nodered.sensor.NodeRedSensor'>) implements device_state_attributes. Please report it to the custom component author.
2021-12-19 10:10:25 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.watermelon_boot_free_disk_space_in_gb (<class 'custom_components.nodered.sensor.NodeRedSensor'>) implements device_state_attributes. Please report it to the custom component author.
2021-12-19 10:10:25 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.watermelon_boot_percent_of_disk_used (<class 'custom_components.nodered.sensor.NodeRedSensor'>) implements device_state_attributes. Please report it to the custom component author.
2021-12-19 10:10:38 ERROR (MainThread) [snitun.client.client_peer] Challenge/Response error with SniTun server (0 bytes read on a total of 32 expected bytes)
2021-12-19 10:10:38 ERROR (MainThread) [hass_nabucasa.remote] Connection problem to snitun server
2021-12-19 10:56:21 ERROR (SyncWorker_4) [custom_components.hildebrandglow_dcc.glow] Glow response status code: 500 (https://api.glowmarkt.com/api/v0-1/resource/6d8dbccc-d02e-442e-a6f0-e97244f45b4a/readings?from=2021-01-01T00:00:00&to=2021-12-19T23:59:59&period=P1Y&offset=0&function=sum)
2021-12-19 10:56:21 ERROR (SyncWorker_5) [custom_components.hildebrandglow_dcc.glow] Glow response status code: 500 (https://api.glowmarkt.com/api/v0-1/resource/e596c4c2-7e66-4976-b130-b57e339b3d74/readings?from=2021-01-01T00:00:00&to=2021-12-19T23:59:59&period=P1Y&offset=0&function=sum)
2021-12-19 10:56:21 ERROR (SyncWorker_8) [custom_components.hildebrandglow_dcc.glow] Glow response status code: 500 (https://api.glowmarkt.com/api/v0-1/resource/6d8dbccc-d02e-442e-a6f0-e97244f45b4a/tariff)
2021-12-19 10:56:21 ERROR (SyncWorker_3) [custom_components.hildebrandglow_dcc.glow] Glow response status code: 500 (https://api.glowmarkt.com/api/v0-1/resource/e596c4c2-7e66-4976-b130-b57e339b3d74/tariff)
2021-12-19 10:56:21 ERROR (SyncWorker_0) [custom_components.hildebrandglow_dcc.glow] Glow response status code: 500 (https://api.glowmarkt.com/api/v0-1/resource/6d8dbccc-d02e-442e-a6f0-e97244f45b4a/readings?from=2021-12-19T00:00:00&to=2021-12-19T23:59:59&period=P1D&offset=0&function=sum)
2021-12-19 10:56:21 ERROR (SyncWorker_7) [custom_components.hildebrandglow_dcc.glow] Glow response status code: 500 (https://api.glowmarkt.com/api/v0-1/resource/4a22d2ce-6518-4e0f-ba60-8a61b81f3e08/readings?from=2021-12-19T00:00:00&to=2021-12-19T23:59:59&period=P1D&offset=0&function=sum)
2021-12-19 10:56:21 ERROR (SyncWorker_1) [custom_components.hildebrandglow_dcc.glow] Glow response status code: 500 (https://api.glowmarkt.com/api/v0-1/resource/e596c4c2-7e66-4976-b130-b57e339b3d74/readings?from=2021-12-19T00:00:00&to=2021-12-19T23:59:59&period=P1D&offset=0&function=sum)
2021-12-19 10:56:21 ERROR (SyncWorker_9) [custom_components.hildebrandglow_dcc.glow] Glow response status code: 500 (https://api.glowmarkt.com/api/v0-1/resource/76655d58-a29e-4642-8f5b-e41cbc06206e/readings?from=2021-12-19T00:00:00&to=2021-12-19T23:59:59&period=P1D&offset=0&function=sum)
2021-12-19 11:22:41 ERROR (MainThread) [homeassistant.components.shelly] Error fetching Forest room Sensor data: Sleeping device did not update within 3600 seconds interval
2021-12-19 12:09:23 ERROR (Thread-4) [tuya_iot] error while get mqtt config
2021-12-19 13:10:26 WARNING (SyncWorker_5) [urllib3.connectionpool] Retrying (Retry(total=9, connect=9, read=10, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff93379910>: Failed to establish a new connection: [Errno -3] Try again')': /public/data/val/wxfcs/all/json/3672?key=21202dde-c73e-4522-842b-4e57aaa68c45&res=3hourly
2021-12-19 13:10:27 WARNING (SyncWorker_3) [urllib3.connectionpool] Retrying (Retry(total=9, connect=9, read=10, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff93753880>: Failed to establish a new connection: [Errno -3] Try again')': /public/data/val/wxfcs/all/json/3672?key=21202dde-c73e-4522-842b-4e57aaa68c45&res=daily
2021-12-19 13:10:31 WARNING (SyncWorker_5) [urllib3.connectionpool] Retrying (Retry(total=8, connect=8, read=10, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff93647ac0>: Failed to establish a new connection: [Errno -3] Try again')': /public/data/val/wxfcs/all/json/3672?key=21202dde-c73e-4522-842b-4e57aaa68c45&res=3hourly
2021-12-19 13:10:32 WARNING (SyncWorker_3) [urllib3.connectionpool] Retrying (Retry(total=8, connect=8, read=10, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff93788f70>: Failed to establish a new connection: [Errno -3] Try again')': /public/data/val/wxfcs/all/json/3672?key=21202dde-c73e-4522-842b-4e57aaa68c45&res=daily
2021-12-19 13:10:37 WARNING (SyncWorker_5) [urllib3.connectionpool] Retrying (Retry(total=7, connect=7, read=10, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff918c0d30>: Failed to establish a new connection: [Errno -3] Try again')': /public/data/val/wxfcs/all/json/3672?key=21202dde-c73e-4522-842b-4e57aaa68c45&res=3hourly
2021-12-19 13:10:38 WARNING (SyncWorker_3) [urllib3.connectionpool] Retrying (Retry(total=7, connect=7, read=10, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff93711d90>: Failed to establish a new connection: [Errno -3] Try again')': /public/data/val/wxfcs/all/json/3672?key=21202dde-c73e-4522-842b-4e57aaa68c45&res=daily
2021-12-19 13:10:45 WARNING (SyncWorker_5) [urllib3.connectionpool] Retrying (Retry(total=6, connect=6, read=10, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff95d7e910>: Failed to establish a new connection: [Errno -3] Try again')': /public/data/val/wxfcs/all/json/3672?key=21202dde-c73e-4522-842b-4e57aaa68c45&res=3hourly
2021-12-19 13:10:46 WARNING (SyncWorker_3) [urllib3.connectionpool] Retrying (Retry(total=6, connect=6, read=10, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff918a69a0>: Failed to establish a new connection: [Errno -3] Try again')': /public/data/val/wxfcs/all/json/3672?key=21202dde-c73e-4522-842b-4e57aaa68c45&res=daily
2021-12-19 13:10:55 WARNING (SyncWorker_5) [urllib3.connectionpool] Retrying (Retry(total=5, connect=5, read=10, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff9185c6a0>: Failed to establish a new connection: [Errno -3] Try again')': /public/data/val/wxfcs/all/json/3672?key=21202dde-c73e-4522-842b-4e57aaa68c45&res=3hourly
2021-12-19 13:10:56 WARNING (SyncWorker_3) [urllib3.connectionpool] Retrying (Retry(total=5, connect=5, read=10, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff9185c8e0>: Failed to establish a new connection: [Errno -3] Try again')': /public/data/val/wxfcs/all/json/3672?key=21202dde-c73e-4522-842b-4e57aaa68c45&res=daily
2021-12-19 13:11:09 WARNING (SyncWorker_5) [urllib3.connectionpool] Retrying (Retry(total=4, connect=4, read=10, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffffa1e00250>: Failed to establish a new connection: [Errno -3] Try again')': /public/data/val/wxfcs/all/json/3672?key=21202dde-c73e-4522-842b-4e57aaa68c45&res=3hourly
2021-12-19 13:11:10 WARNING (SyncWorker_3) [urllib3.connectionpool] Retrying (Retry(total=4, connect=4, read=10, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffffa1e007f0>: Failed to establish a new connection: [Errno -3] Try again')': /public/data/val/wxfcs/all/json/3672?key=21202dde-c73e-4522-842b-4e57aaa68c45&res=daily
2021-12-19 13:11:33 WARNING (SyncWorker_5) [urllib3.connectionpool] Retrying (Retry(total=3, connect=3, read=10, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff918633a0>: Failed to establish a new connection: [Errno -3] Try again')': /public/data/val/wxfcs/all/json/3672?key=21202dde-c73e-4522-842b-4e57aaa68c45&res=3hourly
2021-12-19 13:11:34 WARNING (SyncWorker_3) [urllib3.connectionpool] Retrying (Retry(total=3, connect=3, read=10, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff918c3250>: Failed to establish a new connection: [Errno -3] Try again')': /public/data/val/wxfcs/all/json/3672?key=21202dde-c73e-4522-842b-4e57aaa68c45&res=daily
2021-12-19 13:37:43 WARNING (MainThread) [hass_nabucasa.iot] Unable to connect: Cannot connect to host cloud.nabucasa.com:443 ssl:default [Try again]
2021-12-19 13:37:56 WARNING (MainThread) [hass_nabucasa.iot] Unable to connect: Cannot connect to host cloud.nabucasa.com:443 ssl:default [Try again]
2021-12-19 13:38:01 WARNING (SyncWorker_4) [urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=False, redirect=None, status=3)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff91854670>: Failed to establish a new connection: [Errno -3] Try again')': /v1/me/player
2021-12-19 13:38:06 WARNING (MainThread) [homeassistant.helpers.entity] Update of media_player.spotify_eamonn_sullivan is taking over 10 seconds
2021-12-19 13:38:07 WARNING (SyncWorker_4) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=False, redirect=None, status=3)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9336b4c0>: Failed to establish a new connection: [Errno -3] Try again')': /v1/me/player
2021-12-19 13:38:10 WARNING (MainThread) [hass_nabucasa.iot] Unable to connect: Cannot connect to host cloud.nabucasa.com:443 ssl:default [Try again]
2021-12-19 13:38:13 WARNING (SyncWorker_4) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=False, redirect=None, status=3)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff91839910>: Failed to establish a new connection: [Errno -3] Try again')': /v1/me/player
2021-12-19 13:38:26 WARNING (SyncWorker_0) [custom_components.hildebrandglow_dcc.glow] Error connecting to Glow HTTPSConnectionPool(host='api.glowmarkt.com', port=443): Max retries exceeded with url: /api/v0-1/resource/6d8dbccc-d02e-442e-a6f0-e97244f45b4a/readings?from=2021-01-01T00:00:00&to=2021-12-19T23:59:59&period=P1Y&offset=0&function=sum (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff936f98b0>: Failed to establish a new connection: [Errno -3] Try again'))
2021-12-19 13:38:26 WARNING (SyncWorker_2) [custom_components.hildebrandglow_dcc.glow] Error connecting to Glow HTTPSConnectionPool(host='api.glowmarkt.com', port=443): Max retries exceeded with url: /api/v0-1/resource/e596c4c2-7e66-4976-b130-b57e339b3d74/readings?from=2021-01-01T00:00:00&to=2021-12-19T23:59:59&period=P1Y&offset=0&function=sum (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff936f92b0>: Failed to establish a new connection: [Errno -3] Try again'))
2021-12-19 13:38:26 WARNING (SyncWorker_3) [custom_components.hildebrandglow_dcc.glow] Error connecting to Glow HTTPSConnectionPool(host='api.glowmarkt.com', port=443): Max retries exceeded with url: /api/v0-1/resource/6d8dbccc-d02e-442e-a6f0-e97244f45b4a/tariff (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff936f96d0>: Failed to establish a new connection: [Errno -3] Try again'))
2021-12-19 13:38:26 WARNING (SyncWorker_9) [custom_components.hildebrandglow_dcc.glow] Error connecting to Glow HTTPSConnectionPool(host='api.glowmarkt.com', port=443): Max retries exceeded with url: /api/v0-1/resource/6d8dbccc-d02e-442e-a6f0-e97244f45b4a/catchup (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff936f9c70>: Failed to establish a new connection: [Errno -3] Try again'))
2021-12-19 13:38:26 WARNING (SyncWorker_5) [custom_components.hildebrandglow_dcc.glow] Error connecting to Glow HTTPSConnectionPool(host='api.glowmarkt.com', port=443): Max retries exceeded with url: /api/v0-1/resource/e596c4c2-7e66-4976-b130-b57e339b3d74/tariff (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff936f99d0>: Failed to establish a new connection: [Errno -3] Try again'))
2021-12-19 13:38:26 WARNING (SyncWorker_6) [custom_components.hildebrandglow_dcc.glow] Error connecting to Glow HTTPSConnectionPool(host='api.glowmarkt.com', port=443): Max retries exceeded with url: /api/v0-1/resource/e596c4c2-7e66-4976-b130-b57e339b3d74/catchup (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff936f9d90>: Failed to establish a new connection: [Errno -3] Try again'))
2021-12-19 13:38:26 WARNING (SyncWorker_4) [custom_components.hildebrandglow_dcc.glow] Error connecting to Glow HTTPSConnectionPool(host='api.glowmarkt.com', port=443): Max retries exceeded with url: /api/v0-1/resource/76655d58-a29e-4642-8f5b-e41cbc06206e/catchup (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff936f9df0>: Failed to establish a new connection: [Errno -3] Try again'))
2021-12-19 13:38:26 WARNING (SyncWorker_8) [custom_components.hildebrandglow_dcc.glow] Error connecting to Glow HTTPSConnectionPool(host='api.glowmarkt.com', port=443): Max retries exceeded with url: /api/v0-1/resource/4a22d2ce-6518-4e0f-ba60-8a61b81f3e08/catchup (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa215aca0>: Failed to establish a new connection: [Errno -3] Try again'))
2021-12-19 13:38:31 WARNING (SyncWorker_1) [urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=False, redirect=None, status=3)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff917db820>: Failed to establish a new connection: [Errno -3] Try again')': /v1/me/player
2021-12-19 13:38:31 WARNING (MainThread) [hass_nabucasa.iot] Unable to connect: Cannot connect to host cloud.nabucasa.com:443 ssl:default [Try again]
2021-12-19 13:38:36 WARNING (MainThread) [homeassistant.helpers.entity] Update of media_player.spotify_eamonn_sullivan is taking over 10 seconds
2021-12-19 13:38:37 WARNING (SyncWorker_1) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=False, redirect=None, status=3)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff917fe700>: Failed to establish a new connection: [Errno -3] Try again')': /v1/me/player
2021-12-19 13:38:43 WARNING (SyncWorker_1) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=False, redirect=None, status=3)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff917db520>: Failed to establish a new connection: [Errno -3] Try again')': /v1/me/player
2021-12-19 13:39:01 WARNING (SyncWorker_5) [urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=False, redirect=None, status=3)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff917f8c70>: Failed to establish a new connection: [Errno -3] Try again')': /v1/me/player
2021-12-19 13:39:06 WARNING (MainThread) [homeassistant.helpers.entity] Update of media_player.spotify_eamonn_sullivan is taking over 10 seconds
2021-12-19 13:39:07 WARNING (SyncWorker_5) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=False, redirect=None, status=3)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff918972e0>: Failed to establish a new connection: [Errno -3] Try again')': /v1/me/player
2021-12-19 13:39:13 WARNING (SyncWorker_5) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=False, redirect=None, status=3)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff917f8790>: Failed to establish a new connection: [Errno -3] Try again')': /v1/me/player
2021-12-19 13:39:31 WARNING (SyncWorker_0) [urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=False, redirect=None, status=3)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9150ed00>: Failed to establish a new connection: [Errno -3] Try again')': /v1/me/player
2021-12-19 13:39:36 WARNING (MainThread) [homeassistant.helpers.entity] Update of media_player.spotify_eamonn_sullivan is taking over 10 seconds
2021-12-19 13:39:37 WARNING (SyncWorker_0) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=False, redirect=None, status=3)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff917f8af0>: Failed to establish a new connection: [Errno -3] Try again')': /v1/me/player
2021-12-19 13:39:43 WARNING (SyncWorker_0) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=False, redirect=None, status=3)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff917f8b80>: Failed to establish a new connection: [Errno -3] Try again')': /v1/me/player
2021-12-19 13:40:01 WARNING (SyncWorker_5) [urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=False, redirect=None, status=3)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff917db4c0>: Failed to establish a new connection: [Errno -3] Try again')': /v1/me/player
2021-12-19 13:40:06 WARNING (MainThread) [homeassistant.helpers.entity] Update of media_player.spotify_eamonn_sullivan is taking over 10 seconds
2021-12-19 13:40:07 WARNING (SyncWorker_5) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=False, redirect=None, status=3)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff91509af0>: Failed to establish a new connection: [Errno -3] Try again')': /v1/me/player
2021-12-19 13:40:13 WARNING (SyncWorker_5) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=False, redirect=None, status=3)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9335ff40>: Failed to establish a new connection: [Errno -3] Try again')': /v1/me/player
2021-12-19 13:40:26 ERROR (MainThread) [homeassistant.components.co2signal] Error requesting co2signal data: HTTPSConnectionPool(host='api.co2signal.com', port=443): Max retries exceeded with url: /v1/latest?lon=-0.39422571659088135&lat=51.56566658426592 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff91839fa0>: Failed to establish a new connection: [Errno -3] Try again'))
2021-12-19 13:40:26 WARNING (SyncWorker_0) [custom_components.hildebrandglow_dcc.glow] Error connecting to Glow HTTPSConnectionPool(host='api.glowmarkt.com', port=443): Max retries exceeded with url: /api/v0-1/resource/6d8dbccc-d02e-442e-a6f0-e97244f45b4a/tariff (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9150e550>: Failed to establish a new connection: [Errno -3] Try again'))
2021-12-19 13:40:26 WARNING (SyncWorker_7) [custom_components.hildebrandglow_dcc.glow] Error connecting to Glow HTTPSConnectionPool(host='api.glowmarkt.com', port=443): Max retries exceeded with url: /api/v0-1/resource/6d8dbccc-d02e-442e-a6f0-e97244f45b4a/catchup (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff91849130>: Failed to establish a new connection: [Errno -3] Try again'))
2021-12-19 13:40:26 WARNING (SyncWorker_8) [custom_components.hildebrandglow_dcc.glow] Error connecting to Glow HTTPSConnectionPool(host='api.glowmarkt.com', port=443): Max retries exceeded with url: /api/v0-1/resource/e596c4c2-7e66-4976-b130-b57e339b3d74/catchup (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff91849700>: Failed to establish a new connection: [Errno -3] Try again'))
2021-12-19 13:40:26 WARNING (SyncWorker_5) [custom_components.hildebrandglow_dcc.glow] Error connecting to Glow HTTPSConnectionPool(host='api.glowmarkt.com', port=443): Max retries exceeded with url: /api/v0-1/resource/e596c4c2-7e66-4976-b130-b57e339b3d74/readings?from=2021-01-01T00:00:00&to=2021-12-19T23:59:59&period=P1Y&offset=0&function=sum (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff918491f0>: Failed to establish a new connection: [Errno -3] Try again'))
2021-12-19 13:40:26 WARNING (SyncWorker_6) [custom_components.hildebrandglow_dcc.glow] Error connecting to Glow HTTPSConnectionPool(host='api.glowmarkt.com', port=443): Max retries exceeded with url: /api/v0-1/resource/6d8dbccc-d02e-442e-a6f0-e97244f45b4a/readings?from=2021-01-01T00:00:00&to=2021-12-19T23:59:59&period=P1Y&offset=0&function=sum (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff918b53a0>: Failed to establish a new connection: [Errno -3] Try again'))
2021-12-19 13:40:26 WARNING (SyncWorker_1) [custom_components.hildebrandglow_dcc.glow] Error connecting to Glow HTTPSConnectionPool(host='api.glowmarkt.com', port=443): Max retries exceeded with url: /api/v0-1/resource/e596c4c2-7e66-4976-b130-b57e339b3d74/tariff (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff936f9280>: Failed to establish a new connection: [Errno -3] Try again'))
2021-12-19 13:40:26 WARNING (SyncWorker_9) [custom_components.hildebrandglow_dcc.glow] Error connecting to Glow HTTPSConnectionPool(host='api.glowmarkt.com', port=443): Max retries exceeded with url: /api/v0-1/resource/76655d58-a29e-4642-8f5b-e41cbc06206e/catchup (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffaa4eb7c0>: Failed to establish a new connection: [Errno -3] Try again'))
2021-12-19 13:40:26 WARNING (SyncWorker_3) [custom_components.hildebrandglow_dcc.glow] Error connecting to Glow HTTPSConnectionPool(host='api.glowmarkt.com', port=443): Max retries exceeded with url: /api/v0-1/resource/4a22d2ce-6518-4e0f-ba60-8a61b81f3e08/catchup (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff92a35d30>: Failed to establish a new connection: [Errno -3] Try again'))
2021-12-19 13:40:31 WARNING (SyncWorker_4) [urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=False, redirect=None, status=3)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff91821fa0>: Failed to establish a new connection: [Errno -3] Try again')': /v1/me/player
2021-12-19 13:40:36 WARNING (MainThread) [homeassistant.helpers.entity] Update of media_player.spotify_eamonn_sullivan is taking over 10 seconds
2021-12-19 13:40:37 WARNING (SyncWorker_4) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=False, redirect=None, status=3)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff917dbbb0>: Failed to establish a new connection: [Errno -3] Try again')': /v1/me/player
2021-12-19 13:40:43 WARNING (SyncWorker_4) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=False, redirect=None, status=3)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff91839880>: Failed to establish a new connection: [Errno -3] Try again')': /v1/me/player
2021-12-19 14:08:23 ERROR (Thread-4) [tuya_iot] error while get mqtt config
2021-12-19 14:31:49 ERROR (MainThread) [homeassistant.components.switch] Platform mqtt does not generate unique IDs. ID zwavejs2mqtt_0xea18c216_3-37-0-currentValue already exists - ignoring switch.macbook_charger_switch
2021-12-19 14:31:49 ERROR (MainThread) [homeassistant.components.sensor] Platform mqtt does not generate unique IDs. ID zwavejs2mqtt_0xea18c216_3-50-0-value-65537 already exists - ignoring sensor.macbook_charger_electric_kwh_value
2021-12-19 14:31:49 ERROR (MainThread) [homeassistant.components.sensor] Platform mqtt does not generate unique IDs. ID zwavejs2mqtt_0xea18c216_3-50-0-value-66049 already exists - ignoring sensor.macbook_charger_electric_w_value
2021-12-19 14:31:49 ERROR (MainThread) [homeassistant.components.binary_sensor] Platform mqtt does not generate unique IDs. ID zwavejs2mqtt_0xea18c216_3-113-0-Power_Management-Over-current_status already exists - ignoring binary_sensor.macbook_charger_over_current_status
2021-12-19 14:31:49 ERROR (MainThread) [homeassistant.components.binary_sensor] Platform mqtt does not generate unique IDs. ID zwavejs2mqtt_0xea18c216_3-113-0-Power_Management-Over-load_status already exists - ignoring binary_sensor.macbook_charger_over_load_status
2021-12-19 14:31:49 ERROR (MainThread) [homeassistant.components.binary_sensor] Platform mqtt does not generate unique IDs. ID zwavejs2mqtt_0xea18c216_3-113-0-System-Hardware_status already exists - ignoring binary_sensor.macbook_charger_hardware_status
2021-12-19 14:34:19 WARNING (MainThread) [homeassistant.components.cloud.google_config] Error reporting state - 5: Requested entity was not found.
2021-12-19 14:35:20 ERROR (MainThread) [homeassistant.components.zwave_js] Failed to connect: Server disconnected
2021-12-19 14:35:20 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Z-Wave JS' for zwave_js integration not ready yet: Server disconnected; Retrying in background
2021-12-19 15:12:36 ERROR (SyncWorker_2) [pyicloud.base] Authentication required for Account. (421)
2021-12-19 16:07:23 ERROR (Thread-4) [tuya_iot] error while get mqtt config
2021-12-19 18:06:24 ERROR (Thread-4) [tuya_iot] error while get mqtt config
2021-12-19 18:28:20 WARNING (MainThread) [homeassistant.components.cloud.google_config] Error reporting state - 5: Requested entity was not found.
2021-12-19 18:29:14 WARNING (MainThread) [homeassistant.components.cloud.google_config] Error reporting state - 5: Requested entity was not found.
2021-12-19 18:53:33 WARNING (MainThread) [homeassistant.components.cloud.google_config] Error reporting state - 5: Requested entity was not found.
2021-12-19 19:06:10 WARNING (MainThread) [homeassistant.components.cloud.google_config] Error reporting state - 5: Requested entity was not found.
2021-12-19 19:19:15 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities light.christmas_tree
2021-12-19 19:19:26 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities light.christmas_tree
2021-12-19 19:21:39 WARNING (MainThread) [homeassistant.components.cloud.google_config] Error reporting state - 5: Requested entity was not found.
2021-12-19 19:33:30 WARNING (MainThread) [homeassistant.components.cloud.google_config] Error reporting state - 5: Requested entity was not found.
2021-12-19 19:34:10 WARNING (MainThread) [homeassistant.components.cloud.google_config] Error reporting state - 5: Requested entity was not found.
2021-12-19 19:44:43 WARNING (MainThread) [homeassistant.components.cloud.google_config] Error reporting state - 5: Requested entity was not found.
2021-12-19 19:45:04 WARNING (MainThread) [homeassistant.helpers.frame] Detected integration that uses str for device registry disabled_by. This is deprecated and will stop working in Home Assistant 2022.3, it should be updated to use DeviceEntryDisabler instead. Please report issue for config using this method at homeassistant/components/config/device_registry.py, line 65: entry = registry.async_update_device(**msg)
2021-12-19 20:05:24 ERROR (Thread-4) [tuya_iot] error while get mqtt config
