2022-03-13 22:32:14 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hildebrandglow_dcc which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-03-13 22:32:14 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration nodered which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-03-13 22:32:23 WARNING (MainThread) [homeassistant.components.mqtt] The 'broker' option near /config/configuration.yaml:79 is deprecated, please remove it from your configuration
2022-03-13 22:32:24 WARNING (MainThread) [hass_nabucasa.cloud_api] Fetched https://alexa-api.nabucasa.com/access_token (400)
2022-03-13 22:32:29 ERROR (MainThread) [homeassistant.components.mqtt] Failed to connect to MQTT server due to exception: timed out
2022-03-13 23:30:13 WARNING (Thread-6) [pychromecast.socket_client] [office speaker(192.168.50.76):8009] Heartbeat timeout, resetting connection
2022-03-13 23:30:46 ERROR (Thread-6) [pychromecast.socket_client] [office speaker(192.168.50.76):8009] Failed to connect to service ServiceInfo(type='host', data=('192.168.50.76', 8009)), retrying in 5.0s
2022-03-14 04:54:55 WARNING (Thread-7) [pychromecast.socket_client] [Living room speaker(192.168.50.52):8009] Heartbeat timeout, resetting connection
2022-03-14 04:55:03 ERROR (Thread-7) [pychromecast.socket_client] [Living room speaker(192.168.50.52):8009] Failed to connect to service ServiceInfo(type='host', data=('192.168.50.52', 8009)), retrying in 5.0s
2022-03-14 15:09:44 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities script.doorbell
2022-03-14 15:17:25 ERROR (SyncWorker_13) [homeassistant.components.co2signal] Unexpected exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.9/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/co2signal/__init__.py", line 119, in get_data
    data = CO2Signal.get_latest(
  File "/usr/local/lib/python3.9/site-packages/CO2Signal/co2signal.py", line 34, in get_latest
    latest_data = (requests
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 917, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: [Errno Expecting value] <!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en-US"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en-US"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en-US"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en-US"> <!--<![endif]-->
<head>
<meta http-equiv="refresh" content="0">

<title>api.co2signal.com | 502: Bad gateway</title>
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/main.css" type="text/css" media="screen,projection" />


<script type="text/javascript">
(function(){if(document.addEventListener&&window.XMLHttpRequest&&JSON&&JSON.stringify){var e=function(a){var c=document.getElementById("error-feedback-survey"),d=document.getElementById("error-feedback-success"),b=new XMLHttpRequest;a={event:"feedback clicked",properties:{errorCode:502,helpful:a,version:1}};b.open("POST","https://sparrow.cloudflare.com/api/v1/event");b.setRequestHeader("Content-Type","application/json");b.setRequestHeader("Sparrow-Source-Key","c771f0e4b54944bebf4261d44bd79a1e");
b.send(JSON.stringify(a));c.classList.add("feedback-hidden");d.classList.remove("feedback-hidden")};document.addEventListener("DOMContentLoaded",function(){var a=document.getElementById("error-feedback"),c=document.getElementById("feedback-button-yes"),d=document.getElementById("feedback-button-no");"classList"in a&&(a.classList.remove("feedback-hidden"),c.addEventListener("click",function(){e(!0)}),d.addEventListener("click",function(){e(!1)}))})}})();
</script>

</head>
<body>
<div id="cf-wrapper">

    

    <div id="cf-error-details" class="p-0">
        <header class="mx-auto pt-10 lg:pt-6 lg:px-8 w-240 lg:w-full mb-8">
            <h1 class="inline-block sm:block sm:mb-2 font-light text-60 lg:text-4xl text-black-dark leading-tight mr-2">
              
              <span class="cf-error-type">Error</span>
              <span class="cf-error-code">502</span>
            </h1>
            <span class="inline-block sm:block font-mono text-15 lg:text-sm lg:leading-relaxed">Ray ID: 6ebdf9e019cf3601 &bull;</span>
            <span class="inline-block sm:block font-mono text-15 lg:text-sm lg:leading-relaxed">2022-03-14 15:17:25 UTC</span>
            <h2 class="text-gray-600 leading-1.3 text-3xl font-light">Bad gateway</h2>
        </header>
        
        <div class="my-8 bg-gradient-gray">
            <div class="w-240 lg:w-full mx-auto">
                <div class="clearfix md:px-8">
                  
<div id="cf-browser-status" class=" relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center">
  <div class="relative mb-10 md:m-0">
    <span class="cf-icon-browser block md:hidden h-20 bg-center bg-no-repeat"></span>
    <span class="cf-icon-ok w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4"></span>
  </div>
  <span class="md:block w-full truncate">You</span>
  <h3 class="md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3">Browser</h3>
  <span class="leading-1.3 text-2xl text-green-success">Working</span>
</div>

<div id="cf-cloudflare-status" class=" relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center">
  <div class="relative mb-10 md:m-0">
    <span class="cf-icon-cloud block md:hidden h-20 bg-center bg-no-repeat"></span>
    <span class="cf-icon-ok w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4"></span>
  </div>
  <span class="md:block w-full truncate">Manchester</span>
  <h3 class="md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3">Cloudflare</h3>
  <span class="leading-1.3 text-2xl text-green-success">Working</span>
</div>

<div id="cf-host-status" class="cf-error-source relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center">
  <div class="relative mb-10 md:m-0">
    <span class="cf-icon-server block md:hidden h-20 bg-center bg-no-repeat"></span>
    <span class="cf-icon-error w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4"></span>
  </div>
  <span class="md:block w-full truncate">api.co2signal.com</span>
  <h3 class="md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3">Host</h3>
  <span class="leading-1.3 text-2xl text-red-error">Error</span>
</div>

                </div>
              
            </div>
        </div>

        <div class="w-240 lg:w-full mx-auto mb-8 lg:px-8">
            <div class="clearfix">
                <div class="w-1/2 md:w-full float-left pr-6 md:pb-10 md:pr-0 leading-relaxed">
                    <h2 class="text-3xl font-normal leading-1.3 mb-4">What happened?</h2>
                    <p>The web server reported a bad gateway error.</p>
                </div>
              
                <div class="w-1/2 md:w-full float-left leading-relaxed">
                    <h2 class="text-3xl font-normal leading-1.3 mb-4">What can I do?</h2>
                    <p class="mb-6">Please try again in a few minutes.</p>
                </div>
            </div>
              
        </div>

        
        <div class="feedback-hidden py-8 text-center" id="error-feedback">
           <div id="error-feedback-survey">
              Was this page helpful?
              <button class="border border-solid bg-white cf-button cursor-pointer ml-4 px-4 py-2 rounded" id="feedback-button-yes" type="button">Yes</button>
              <button class="border border-solid bg-white cf-button cursor-pointer ml-4 px-4 py-2 rounded" id="feedback-button-no" type="button">No</button>
           </div>
           <div class="feedback-success feedback-hidden" id="error-feedback-success">
              Thank you for your feedback!
           </div>
        </div>
        

        <div class="cf-error-footer cf-wrapper w-240 lg:w-full py-10 sm:py-4 sm:px-8 mx-auto text-center sm:text-left border-solid border-0 border-t border-gray-300">
  <p class="text-13">
    <span class="cf-footer-item sm:block sm:mb-1">Cloudflare Ray ID: <strong class="font-semibold">6ebdf9e019cf3601</strong></span>
    <span class="cf-footer-separator sm:hidden">&bull;</span>
    <span class="cf-footer-item sm:block sm:mb-1"><span>Your IP</span>: 82.41.62.226</span>
    <span class="cf-footer-separator sm:hidden">&bull;</span>
    <span class="cf-footer-item sm:block sm:mb-1"><span>Performance &amp; security by</span> <a rel="noopener noreferrer" href="https://www.cloudflare.com/5xx-error-landing" id="brand_link" target="_blank">Cloudflare</a></span>
    
  </p>
</div><!-- /.error-footer -->


    </div>
</div>
</body>
</html>

: 0
2022-03-14 15:17:25 ERROR (MainThread) [homeassistant.components.co2signal] Error fetching co2signal data: 
2022-03-14 16:15:16 WARNING (MainThread) [homeassistant.components.cloud.google_config] Error reporting state - 14: The service is currently unavailable.
2022-03-14 17:36:07 WARNING (SyncWorker_12) [urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=False, redirect=None, status=3)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff96977a30>: Failed to establish a new connection: [Errno -3] Try again')': /v1/me/player
2022-03-14 17:36:12 WARNING (MainThread) [homeassistant.helpers.entity] Update of media_player.spotify_eamonn_sullivan is taking over 10 seconds
2022-03-14 17:36:12 WARNING (SyncWorker_12) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=False, redirect=None, status=3)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa510a850>: Failed to establish a new connection: [Errno -3] Try again')': /v1/me/player
2022-03-14 17:36:19 WARNING (SyncWorker_12) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=False, redirect=None, status=3)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa5271f40>: Failed to establish a new connection: [Errno -3] Try again')': /v1/me/player
2022-03-14 17:36:31 WARNING (SyncWorker_13) [custom_components.hildebrandglow_dcc.glow] Error connecting to Glow HTTPSConnectionPool(host='api.glowmarkt.com', port=443): Max retries exceeded with url: /api/v0-1/resource/6d8dbccc-d02e-442e-a6f0-e97244f45b4a/catchup (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff971c9d30>: Failed to establish a new connection: [Errno -3] Try again'))
2022-03-14 17:36:31 WARNING (SyncWorker_4) [custom_components.hildebrandglow_dcc.glow] Error connecting to Glow HTTPSConnectionPool(host='api.glowmarkt.com', port=443): Max retries exceeded with url: /api/v0-1/resource/76655d58-a29e-4642-8f5b-e41cbc06206e/catchup (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff97173820>: Failed to establish a new connection: [Errno -3] Try again'))
2022-03-14 17:36:31 WARNING (SyncWorker_0) [custom_components.hildebrandglow_dcc.glow] Error connecting to Glow HTTPSConnectionPool(host='api.glowmarkt.com', port=443): Max retries exceeded with url: /api/v0-1/resource/6d8dbccc-d02e-442e-a6f0-e97244f45b4a/tariff (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff971c9310>: Failed to establish a new connection: [Errno -3] Try again'))
2022-03-14 17:36:31 WARNING (SyncWorker_1) [custom_components.hildebrandglow_dcc.glow] Error connecting to Glow HTTPSConnectionPool(host='api.glowmarkt.com', port=443): Max retries exceeded with url: /api/v0-1/resource/e596c4c2-7e66-4976-b130-b57e339b3d74/catchup (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa5aef670>: Failed to establish a new connection: [Errno -3] Try again'))
2022-03-14 17:36:31 WARNING (SyncWorker_11) [custom_components.hildebrandglow_dcc.glow] Error connecting to Glow HTTPSConnectionPool(host='api.glowmarkt.com', port=443): Max retries exceeded with url: /api/v0-1/resource/6d8dbccc-d02e-442e-a6f0-e97244f45b4a/readings?from=2022-01-01T00:00:00&to=2022-03-14T23:59:59&period=P1Y&offset=0&function=sum (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa0485b20>: Failed to establish a new connection: [Errno -3] Try again'))
2022-03-14 17:36:31 WARNING (SyncWorker_10) [custom_components.hildebrandglow_dcc.glow] Error connecting to Glow HTTPSConnectionPool(host='api.glowmarkt.com', port=443): Max retries exceeded with url: /api/v0-1/resource/4a22d2ce-6518-4e0f-ba60-8a61b81f3e08/catchup (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff971c9e20>: Failed to establish a new connection: [Errno -3] Try again'))
2022-03-14 17:36:31 WARNING (SyncWorker_7) [custom_components.hildebrandglow_dcc.glow] Error connecting to Glow HTTPSConnectionPool(host='api.glowmarkt.com', port=443): Max retries exceeded with url: /api/v0-1/resource/e596c4c2-7e66-4976-b130-b57e339b3d74/readings?from=2022-01-01T00:00:00&to=2022-03-14T23:59:59&period=P1Y&offset=0&function=sum (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff97173dc0>: Failed to establish a new connection: [Errno -3] Try again'))
2022-03-14 17:36:31 WARNING (SyncWorker_9) [custom_components.hildebrandglow_dcc.glow] Error connecting to Glow HTTPSConnectionPool(host='api.glowmarkt.com', port=443): Max retries exceeded with url: /api/v0-1/resource/e596c4c2-7e66-4976-b130-b57e339b3d74/tariff (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff97173610>: Failed to establish a new connection: [Errno -3] Try again'))
2022-03-14 17:36:37 WARNING (SyncWorker_12) [urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=False, redirect=None, status=3)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff95dd29a0>: Failed to establish a new connection: [Errno -3] Try again')': /v1/me/player
2022-03-14 17:36:42 WARNING (MainThread) [homeassistant.helpers.entity] Update of media_player.spotify_eamonn_sullivan is taking over 10 seconds
2022-03-14 17:36:42 WARNING (SyncWorker_12) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=False, redirect=None, status=3)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff95181670>: Failed to establish a new connection: [Errno -3] Try again')': /v1/me/player
2022-03-14 17:36:49 WARNING (SyncWorker_12) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=False, redirect=None, status=3)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff969aba90>: Failed to establish a new connection: [Errno -3] Try again')': /v1/me/player
2022-03-14 17:37:07 WARNING (SyncWorker_4) [urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=False, redirect=None, status=3)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff969a7eb0>: Failed to establish a new connection: [Errno -3] Try again')': /v1/me/player
2022-03-14 17:37:12 WARNING (MainThread) [homeassistant.helpers.entity] Update of media_player.spotify_eamonn_sullivan is taking over 10 seconds
2022-03-14 17:37:12 WARNING (SyncWorker_4) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=False, redirect=None, status=3)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff97196940>: Failed to establish a new connection: [Errno -3] Try again')': /v1/me/player
2022-03-14 17:37:19 WARNING (SyncWorker_4) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=False, redirect=None, status=3)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff93dd86a0>: Failed to establish a new connection: [Errno -3] Try again')': /v1/me/player
2022-03-14 17:37:34 WARNING (SyncWorker_10) [urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=False, redirect=None, status=3)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff991fd1c0>: Failed to establish a new connection: [Errno -3] Try again')': /v1/me/player/devices
2022-03-14 17:37:37 WARNING (SyncWorker_6) [urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=False, redirect=None, status=3)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff95e163a0>: Failed to establish a new connection: [Errno -3] Try again')': /v1/me/player
2022-03-14 17:37:39 WARNING (SyncWorker_10) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=False, redirect=None, status=3)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9717dfd0>: Failed to establish a new connection: [Errno -3] Try again')': /v1/me/player/devices
2022-03-14 17:37:42 WARNING (MainThread) [homeassistant.helpers.entity] Update of media_player.spotify_eamonn_sullivan is taking over 10 seconds
2022-03-14 17:37:42 WARNING (SyncWorker_6) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=False, redirect=None, status=3)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff96e14070>: Failed to establish a new connection: [Errno -3] Try again')': /v1/me/player
2022-03-14 17:37:45 WARNING (SyncWorker_10) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=False, redirect=None, status=3)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff97196370>: Failed to establish a new connection: [Errno -3] Try again')': /v1/me/player/devices
2022-03-14 17:37:47 ERROR (MainThread) [snitun.multiplexer.core] Ping fails, no response from peer
2022-03-14 17:37:49 WARNING (SyncWorker_6) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=False, redirect=None, status=3)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff95e16c40>: Failed to establish a new connection: [Errno -3] Try again')': /v1/me/player
2022-03-14 17:37:50 ERROR (MainThread) [homeassistant.components.spotify] Error fetching Eamonn Sullivan Devices data: 
2022-03-14 17:37:55 ERROR (MainThread) [snitun.client.client_peer] Can't connect to SniTun server eu-west-2-3.ui.nabu.casa:443 with: [Errno -3] Try again
2022-03-14 17:37:55 ERROR (MainThread) [hass_nabucasa.remote] Connection problem to snitun server
2022-03-14 17:38:07 WARNING (SyncWorker_12) [urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=False, redirect=None, status=3)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff93bdf430>: Failed to establish a new connection: [Errno -3] Try again')': /v1/me/player
2022-03-14 23:30:20 WARNING (Thread-6) [pychromecast.socket_client] [office speaker(192.168.50.76):8009] Heartbeat timeout, resetting connection
2022-03-14 23:30:29 ERROR (Thread-6) [pychromecast.socket_client] [office speaker(192.168.50.76):8009] Failed to connect to service ServiceInfo(type='host', data=('192.168.50.76', 8009)), retrying in 5.0s
2022-03-15 00:10:08 WARNING (SyncWorker_3) [urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=False, redirect=None, status=3)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff93734d60>: Failed to establish a new connection: [Errno -3] Try again')': /v1/me/player
2022-03-15 00:10:13 WARNING (MainThread) [homeassistant.helpers.entity] Update of media_player.spotify_eamonn_sullivan is taking over 10 seconds
2022-03-15 00:10:13 WARNING (SyncWorker_3) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=False, redirect=None, status=3)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9516c760>: Failed to establish a new connection: [Errno -3] Try again')': /v1/me/player
2022-03-15 00:10:20 WARNING (SyncWorker_3) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=False, redirect=None, status=3)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff995e3970>: Failed to establish a new connection: [Errno -3] Try again')': /v1/me/player
2022-03-15 00:10:31 WARNING (SyncWorker_6) [custom_components.hildebrandglow_dcc.glow] Error connecting to Glow HTTPSConnectionPool(host='api.glowmarkt.com', port=443): Max retries exceeded with url: /api/v0-1/resource/6d8dbccc-d02e-442e-a6f0-e97244f45b4a/catchup (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff995e36d0>: Failed to establish a new connection: [Errno -3] Try again'))
2022-03-15 00:10:31 WARNING (SyncWorker_4) [custom_components.hildebrandglow_dcc.glow] Error connecting to Glow HTTPSConnectionPool(host='api.glowmarkt.com', port=443): Max retries exceeded with url: /api/v0-1/resource/e596c4c2-7e66-4976-b130-b57e339b3d74/catchup (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff96d92850>: Failed to establish a new connection: [Errno -3] Try again'))
2022-03-15 00:10:31 WARNING (SyncWorker_2) [custom_components.hildebrandglow_dcc.glow] Error connecting to Glow HTTPSConnectionPool(host='api.glowmarkt.com', port=443): Max retries exceeded with url: /api/v0-1/resource/e596c4c2-7e66-4976-b130-b57e339b3d74/tariff (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff96d8d7f0>: Failed to establish a new connection: [Errno -3] Try again'))
2022-03-15 00:10:31 WARNING (SyncWorker_12) [custom_components.hildebrandglow_dcc.glow] Error connecting to Glow HTTPSConnectionPool(host='api.glowmarkt.com', port=443): Max retries exceeded with url: /api/v0-1/resource/e596c4c2-7e66-4976-b130-b57e339b3d74/readings?from=2022-01-01T00:00:00&to=2022-03-15T23:59:59&period=P1Y&offset=0&function=sum (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff96d8d4f0>: Failed to establish a new connection: [Errno -3] Try again'))
2022-03-15 00:10:31 WARNING (SyncWorker_1) [custom_components.hildebrandglow_dcc.glow] Error connecting to Glow HTTPSConnectionPool(host='api.glowmarkt.com', port=443): Max retries exceeded with url: /api/v0-1/resource/6d8dbccc-d02e-442e-a6f0-e97244f45b4a/tariff (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff96994400>: Failed to establish a new connection: [Errno -3] Try again'))
2022-03-15 00:10:31 WARNING (SyncWorker_8) [custom_components.hildebrandglow_dcc.glow] Error connecting to Glow HTTPSConnectionPool(host='api.glowmarkt.com', port=443): Max retries exceeded with url: /api/v0-1/resource/6d8dbccc-d02e-442e-a6f0-e97244f45b4a/readings?from=2022-01-01T00:00:00&to=2022-03-15T23:59:59&period=P1Y&offset=0&function=sum (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff994cbe50>: Failed to establish a new connection: [Errno -3] Try again'))
2022-03-15 00:10:31 WARNING (SyncWorker_10) [custom_components.hildebrandglow_dcc.glow] Error connecting to Glow HTTPSConnectionPool(host='api.glowmarkt.com', port=443): Max retries exceeded with url: /api/v0-1/resource/4a22d2ce-6518-4e0f-ba60-8a61b81f3e08/catchup (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffffa5108820>: Failed to establish a new connection: [Errno -3] Try again'))
2022-03-15 00:10:31 WARNING (SyncWorker_0) [custom_components.hildebrandglow_dcc.glow] Error connecting to Glow HTTPSConnectionPool(host='api.glowmarkt.com', port=443): Max retries exceeded with url: /api/v0-1/resource/76655d58-a29e-4642-8f5b-e41cbc06206e/catchup (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff97173dc0>: Failed to establish a new connection: [Errno -3] Try again'))
2022-03-15 00:10:38 WARNING (SyncWorker_13) [urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=False, redirect=None, status=3)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9699a880>: Failed to establish a new connection: [Errno -3] Try again')': /v1/me/player
2022-03-15 00:10:43 WARNING (MainThread) [homeassistant.helpers.entity] Update of media_player.spotify_eamonn_sullivan is taking over 10 seconds
2022-03-15 00:10:43 WARNING (SyncWorker_13) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=False, redirect=None, status=3)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff971a4d00>: Failed to establish a new connection: [Errno -3] Try again')': /v1/me/player
2022-03-15 00:10:50 WARNING (SyncWorker_13) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=False, redirect=None, status=3)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff95181be0>: Failed to establish a new connection: [Errno -3] Try again')': /v1/me/player
2022-03-15 00:11:08 WARNING (SyncWorker_2) [urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=False, redirect=None, status=3)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff96e14df0>: Failed to establish a new connection: [Errno -3] Try again')': /v1/me/player
2022-03-15 00:11:13 WARNING (MainThread) [homeassistant.helpers.entity] Update of media_player.spotify_eamonn_sullivan is taking over 10 seconds
2022-03-15 00:11:13 WARNING (SyncWorker_2) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=False, redirect=None, status=3)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff95df64c0>: Failed to establish a new connection: [Errno -3] Try again')': /v1/me/player
2022-03-15 00:11:20 WARNING (SyncWorker_2) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=False, redirect=None, status=3)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9f5dbdf0>: Failed to establish a new connection: [Errno -3] Try again')': /v1/me/player
2022-03-15 00:11:29 ERROR (MainThread) [snitun.multiplexer.core] Ping fails, no response from peer
2022-03-15 00:11:37 ERROR (MainThread) [snitun.client.client_peer] Can't connect to SniTun server eu-west-2-3.ui.nabu.casa:443 with: [Errno -3] Try again
2022-03-15 00:11:37 ERROR (MainThread) [hass_nabucasa.remote] Connection problem to snitun server
2022-03-15 00:11:38 WARNING (SyncWorker_3) [urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=False, redirect=None, status=3)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff96d86370>: Failed to establish a new connection: [Errno -3] Try again')': /v1/me/player
2022-03-15 00:11:43 WARNING (MainThread) [homeassistant.helpers.entity] Update of media_player.spotify_eamonn_sullivan is taking over 10 seconds
2022-03-15 00:11:43 WARNING (SyncWorker_3) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=False, redirect=None, status=3)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff93d72040>: Failed to establish a new connection: [Errno -3] Try again')': /v1/me/player
2022-03-15 00:11:50 WARNING (SyncWorker_3) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=False, redirect=None, status=3)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff971fd9a0>: Failed to establish a new connection: [Errno -3] Try again')': /v1/me/player
2022-03-15 00:11:52 ERROR (MainThread) [snitun.client.client_peer] Can't connect to SniTun server eu-west-2-3.ui.nabu.casa:443 with: [Errno -3] Try again
2022-03-15 00:11:52 ERROR (MainThread) [hass_nabucasa.remote] Connection problem to snitun server
2022-03-15 00:12:08 WARNING (SyncWorker_13) [urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=False, redirect=None, status=3)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff9516e880>: Failed to establish a new connection: [Errno -3] Try again')': /v1/me/player
2022-03-15 00:12:10 ERROR (MainThread) [snitun.client.client_peer] Can't connect to SniTun server eu-west-2-3.ui.nabu.casa:443 with: [Errno -3] Try again
2022-03-15 00:12:10 ERROR (MainThread) [hass_nabucasa.remote] Connection problem to snitun server
2022-03-15 00:12:13 WARNING (MainThread) [homeassistant.helpers.entity] Update of media_player.spotify_eamonn_sullivan is taking over 10 seconds
2022-03-15 00:12:13 WARNING (SyncWorker_13) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=False, redirect=None, status=3)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff98a11160>: Failed to establish a new connection: [Errno -3] Try again')': /v1/me/player
2022-03-15 00:12:17 WARNING (MainThread) [hass_nabucasa.iot] Unable to connect: Cannot connect to host cloud.nabucasa.com:443 ssl:default [Try again]
2022-03-15 00:12:23 WARNING (MainThread) [hass_nabucasa.google_report_state] Unable to connect: Cannot connect to host remotestate.nabucasa.com:443 ssl:default [Try again]
2022-03-15 04:41:42 WARNING (Thread-7) [pychromecast.socket_client] [Living room speaker(192.168.50.52):8009] Heartbeat timeout, resetting connection
2022-03-15 04:41:49 ERROR (Thread-7) [pychromecast.socket_client] [Living room speaker(192.168.50.52):8009] Failed to connect to service ServiceInfo(type='host', data=('192.168.50.52', 8009)), retrying in 5.0s
2022-03-15 06:08:06 WARNING (MainThread) [homeassistant.components.websocket_api.http.connection] [281473196192576] Disconnected: Did not receive auth message within 10 seconds
2022-03-15 08:30:10 WARNING (Recorder) [homeassistant.components.sensor.recorder] Entity sensor.shed_switch_electric_consumption_kwh from integration zwave_js has state class total_increasing, but its state is negative. Triggered by state -21221144.46 with last_updated set to 2022-03-15T08:28:46.485212+00:00. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+zwave_js%22
